# Generated by Django 5.0.1 on 2024-01-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vacancy_options_alter_vacancy_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'email')},
        ),
    ]
