# Generated by Django 4.2.9 on 2024-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_vacancy_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type',
            field=models.CharField(choices=[('FT', 'Fulltime'), ('PT', 'Parttime'), ('PB', 'Project_based')], default='FT', max_length=55),
        ),
    ]
