# Generated by Django 5.0.1 on 2024-01-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0002_delete_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('specialisation', models.CharField(max_length=55)),
                ('expected_salary', models.IntegerField()),
                ('is_searching', models.BooleanField(default=True)),
            ],
        ),
    ]
