# Generated by Django 5.0.1 on 2024-01-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(default='asasa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='frfrfr', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
    ]
