# Generated by Django 5.0.1 on 2024-01-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_company_ceo_company_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='CEO',
            new_name='ceo',
        ),
    ]
