# Generated by Django 4.2.9 on 2024-01-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_alter_company_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Staffs photo'),
        ),
    ]
