# Generated by Django 4.2.9 on 2024-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_resume_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='worker',
            field=models.ManyToManyField(blank=True, related_name='company', to='worker.worker'),
        ),
    ]
